### ISSUE TITLE
Database coords of vehicle

### ISSUE THREAD

**Issue by griha41** [Pwnoz0r/DayZ-Private-Server#143]
Good day time, I've got a problem. Setup yours clear DayZ Mod server, database is empty.
No coordinates for spawn vehicles, no vehicle classes.
If call MySQL database function "call pMain(1);" < - return 0 vehicles spawned.

How can I fix that?

**Comment by skiperh1n1** [comment]
Run pSpawnVehicle, and will be Ok

**Comment by marvinl97** [comment]
Same problem here. I just used the official sql files now, These are filled with spawns, https://github.com/DayZMod/DayZ/tree/Development/SQL/1.8.7

**Comment by Pwnoz0r** [comment]
@skiperh1n1 is right. Once you have your `object_spawns` table populated this will create the vehicle spawns.

Thanks for pointing that out @marvinl97, when I dumped the tables, I never dumped the original data. Updating that now.

**Comment by griha41** [comment]
With my regards thx.

**Comment by marvinl97** [comment]
@Pwnoz0r I have one more question regarding `object_spawns` . The `object_spawns` table is deprecated since 1.8.7, isn't it? I'm just dealing for the last 3 days with all that DayZ server stuff, so I could be wrong but the last version where it was used was 1.8.5. Then the vehicle stuff changed. (`vehicle_???`) And why the heck aren't these SQL files working for Linux? I have to rename the main tables like `object_data` -> `Object_DATA` (https://github.com/rajkosto/hive/tree/master/Hive/SQL). Is it because Windows is case insensitive? I also wonder why nobody just wrote a Hive library for linux. Is it that hard? There is a arma2oaserver file for linux, so you don't have to use wine. This is all I came across while setting up a server for Linux. 

I would be happy if I could hear a bit from a more experienced person. And sorry if I should have opened a new issue.

**Comment by skiperh1n1** [comment]
@marvinl97 Yes linux more sensitive to case, you can download SQL files for linux and upload to your server, or download finished SQL file here: https://github.com/skiperh1n1/dayz-server-master-db-fix/tree/master/SQL
